version: "3.9"
services:
  service:
    build: .
    ports:
      - "3546:3546"
      - "9090:9090"
      - "9999:9999"
    volumes:
      - "./compose-config.yaml:/etc/evaluation-proxy-config.yaml"
  redis:
    image: "redis:alpine"
