name: Docker Build/Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get BUILD_DATE
        run: |
          echo "BUILD_DATE=$( date -u +'%Y-%m-%dT%H:%M:%SZ' )" >> $GITHUB_ENV
      - name: Docker meta ${{ secrets.DOCKERHUB_USERNAME }}/evaluation-proxy
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: type=semver,pattern={{version}}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/evaluation-proxy

      - name: Build and push ${{ secrets.DOCKERHUB_USERNAME }}/evaluation-proxy
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
          tags: ${{ steps.meta.outputs.tags }}
